name: equb_v3_frontend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  badges: ^3.1.1
  jwt_decoder: ^2.0.1
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^9.2.2
  http: ^1.2.1
  http_parser: ^4.0.0
  syncfusion_flutter_charts: ^26.2.14
  table_calendar: ^3.1.1
  go_router: ^14.2.7
  intl: ^0.19.0
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  timer_count_down: ^2.2.0
  flutter_timer_countdown: ^1.0.7
  slide_countdown: ^1.6.1
  choice: ^2.3.2
  open_settings_plus: ^0.3.3
  logger: ^2.4.0
  file_picker: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.0.4
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Dangrek
      fonts:
        - asset: assets/fonts/Dangrek-Regular.ttf
